/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.test.jsonc --include-runtime=false --env-interface=VfsTestEnv` (hash: 4bdcde0bee4fbb2f5e0598116014def3)
interface __BaseEnv_VfsTestEnv {
	VFS_TEST_BUCKET: R2Bucket;
	VFS_TEST: DurableObjectNamespace<import("./test/worker").TestWorkspaceVfs>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./test/worker");
		durableNamespaces: "TestWorkspaceVfs";
	}
	interface Env extends __BaseEnv_VfsTestEnv {}
}
interface VfsTestEnv extends __BaseEnv_VfsTestEnv {}
