import {
  bracketCommand,
  breakCommand,
  cdCommand,
  colonCommand,
  continueCommand,
  dotCommand,
  echoCommand,
  envCommand,
  exitCommand,
  exportCommand,
  falseCommand,
  getoptsCommand,
  localCommand,
  printfCommand,
  pwdCommand,
  readCommand,
  returnCommand,
  setCommand,
  shiftCommand,
  sourceCommand,
  testCommand,
  trueCommand,
  unsetCommand,
} from "./core.js";
import { commandCommand, printenvCommand, typeCommand, whichCommand } from "./discovery.js";
import {
  basenameCommand,
  catCommand,
  chmodCommand,
  cpCommand,
  dirnameCommand,
  duCommand,
  fileCommand,
  findCommand,
  mkdirCommand,
  mktempCommand,
  mvCommand,
  realpathCommand,
  rmCommand,
  rmdirCommand,
  statCommand,
  touchCommand,
  treeCommand,
} from "./fs.js";
import { helpCommand } from "./help.js";
import { lnCommand, readlinkCommand } from "./link.js";
import { lsCommand } from "./ls.js";
import { sedCommand } from "./sed.js";
import { shCommand } from "./sh.js";
import { dateCommand, exprCommand, sleepCommand } from "./system.js";
import {
  base64Command,
  cmpCommand,
  commCommand,
  cutCommand,
  diffCommand,
  foldCommand,
  grepCommand,
  headCommand,
  joinCommand,
  nlCommand,
  pasteCommand,
  patchCommand,
  seqCommand,
  sha256sumCommand,
  sortCommand,
  tailCommand,
  teeCommand,
  trCommand,
  uniqCommand,
  wcCommand,
} from "./text.js";
import { xargsCommand } from "./xargs.js";

export const defaultShellCommands = [
  colonCommand,
  trueCommand,
  falseCommand,
  echoCommand,
  printfCommand,
  pwdCommand,
  cdCommand,
  exportCommand,
  envCommand,
  unsetCommand,
  readCommand,
  shiftCommand,
  getoptsCommand,
  sourceCommand,
  dotCommand,
  commandCommand,
  typeCommand,
  whichCommand,
  printenvCommand,
  helpCommand,
  shCommand,
  exitCommand,
  setCommand,
  testCommand,
  bracketCommand,
  localCommand,
  returnCommand,
  breakCommand,
  continueCommand,
  catCommand,
  mkdirCommand,
  touchCommand,
  rmCommand,
  rmdirCommand,
  mvCommand,
  cpCommand,
  lsCommand,
  lnCommand,
  readlinkCommand,
  findCommand,
  statCommand,
  chmodCommand,
  duCommand,
  treeCommand,
  basenameCommand,
  dirnameCommand,
  realpathCommand,
  mktempCommand,
  fileCommand,
  sortCommand,
  grepCommand,
  headCommand,
  tailCommand,
  wcCommand,
  teeCommand,
  uniqCommand,
  cutCommand,
  trCommand,
  nlCommand,
  foldCommand,
  pasteCommand,
  cmpCommand,
  diffCommand,
  sha256sumCommand,
  sedCommand,
  commCommand,
  joinCommand,
  patchCommand,
  seqCommand,
  base64Command,
  dateCommand,
  sleepCommand,
  exprCommand,
  xargsCommand,
] as const;
